export const VALIDATION_DEBOUNCE_TIME = 700;
export const SITE_NAME = 'IT Route Limited';
export const INVALID_POSTCODE = 'Invalid postcode!';
export const DISTANCE_OPTIONS = [1, 2, 3, 5, 10, 15, 20, 30, 50, 75, 100];
export const APP_NAME = process.env.REACT_APP_APP_NAME || 'Childcare';
export const MIN_WEBSITE_LENGTH = 8;
export const MAX_WEBSITE_LENGTH = 200;
export const MIN_NAME_LENGTH = 2;
export const MAX_NAME_LENGTH = 100;
export const MIN_FIRSTNAME_LENGTH = 2;
export const MAX_LASTNAME_LENGTH = 100;
export const MIN_SUBJECT_LENGTH = 2;
export const MAX_SUBJECT_LENGTH = 100;
export const MIN_TOWN_LENGTH = 2;
export const MAX_TOWN_LENGTH = 100;
export const MIN_COUNTY_LENGTH = 2;
export const MAX_COUNTY_LENGTH = 100;
export const MIN_SCREENNAME_LENGTH = 2;
export const MAX_SCREENNAME_LENGTH = 100;
export const EMAIL_LENGTH = 150;
export const REGISTERED_OFFICE_ADDRESS =
  process.env.REACT_APP_REGISTERED_OFFICE_ADDRESS || '19 Radcliffe Street, Wolverton, Milton Keynes, England, MK12 5DQ';
export const COUNTRY_OF_INCORPORATION = process.env.REACT_APP_COUNTRY_OF_INCORPORATION || 'UK';
export const CLIENT_HOST_NAME = process.env.REACT_APP_CLIENT_HOST_NAME || 'localhost:3000';
export const CLIENT_WEB_NAME = process.env.REACT_APP_CLIENT_WEB_NAME || 'itroute.co.uk';
export const COMPANY_NAME = process.env.REACT_APP_COMPANY_NAME || 'IT Route Limited';
export const COMPANY_REGISTERED_NUMBER = process.env.REACT_APP_COMPANY_REGISTERED_NUMBER || '11548257';
export const COMPANY_VAT_NUMBER = process.env.REACT_APP_COMPANY_VAT_NUMBER || 'GB 303889095';
export const COMPANY_PHONE_NUMBER = process.env.REACT_APP_COMPANY_PHONE_NUMBER;
export const APP_GATEWAY = process.env.REACT_APP_GATEWAY;
export const APP_CLIENT_AUTHORITY = process.env.REACT_APP_CLIENT_AUTHORITY;
console.log('authority', process.env.REACT_APP_CLIENT_AUTHORITY);
export const APP_CLIENT_ID_ON_IDP = process.env.REACT_APP_CLIENT_ID_ON_IDP;
console.log(APP_CLIENT_ID_ON_IDP);
export const APP_ROOT = process.env.REACT_APP_ROOT_URL;
export const PRIVATE_KEY = process.env.RECAPTCHA_KEY || '6LeHKbwZAAAAAJ5ZVVLxWTUtZhVDPOXZ4aR5YrzW';
export const SECRET_KEY = process.env.REACT_APP_SECRET_KEY;
export const CAPTCHA_ENABLED = process.env.REACT_APP_ENABLE_CAPTCHA === 'true';
